// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'elevation': string;
  'shadow': string;
  'surface': string;
}
export const cssExports: CssExports;
export default cssExports;
